project_name: CNN_TCN_LSTM_KFOLD_Single_Report
experiment_name: testing_hidden_2
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project
notes:
seed: 42
dataset:
  preprocess:
    clutter: False #get_files()
    single: True #get_files()
    fps: 5
    mm_frames_per_sec: data/multimodal/5fps/5fs_single_dataset_tensors.pt #directly loads dataset from data/tactile

model:
  module_name: cnn_tcn_lstm
  pl_class_name : LitMM_CNN_TCN_LSTM
  script_path: models/multi_modal/cnn_tcn_lstm.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  img_size: 32
  lstm_n_features: 3
  lstm_nhid: 75
  lstm_nlayers: 3
  lstm_dropout: 0.1
  cnn_input_channels: 3
  cnn_kernel_size: 3
  tcn_nhid: 75
  tcn_levels: 6
  tcn_kernel_size: 8
  tcn_dropout: 0.1
  lr: 0.0001

train:
  checkpoint_path: logging
  batch_size: 1
  epochs: 10
  n_kfolds: 5
  kfold_path: cross-validation/cnn_tcn_lstm_kfold
