project_name: TCN_KFOLD
experiment_name: tcn_test12
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project
notes: baseline model trained for 10 epochs, kernel size 10, levels 8, dopout 0.1, hid 50, dynamic dilation set to 2
seed: 42
dataset:
  preprocess:
    clutter: True #get_files()
    single: True #get_files()
    tactile_frames_per_sec: data/tactile/with_feature_engineering/single_clutter_3fps.pt #directly loads dataset from data/tactile

model:
  module_name: tcn
  pl_class_name : LitTemporalConvNet
  script_path: models/tcn.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  n_features: 3
  n_hid: 50
  n_levels: 8
  kernel_size: 10
  dropout: 0.3
  lr: 0.001
  stride: 1

train:
  checkpoint_path: logging
  batch_size: 1
  epochs: 10
  n_kfolds: 5
  kfold_path: cross-validation/tcn_kfold
