experiment_name: Encoder_Decoder_LSTM
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project

seed: 42

dataset:
  preprocess:
    data_path: dataset #get_files()
    clutter: True #get_files()
    single: False #get_files()
    frames_per_sec: 1 #15  #read_data()
    feature_engineering: True #True #read_data()
    standardise_data: False #preprocess_dataset()
    normalize_data: True #preprocess_dataset()
    pad_data: True #preprocess_dataset()


model:
  module_name: encoder_decoder_lstm
  pl_class_name : LitEncoderDecoderLSTM
  script_path: models/encoder_decoder_lstm.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  n_features: 2 #3
  n_layers: 1
  n_hidden_units: 250 #100 #250

train:
  checkpoint_path: train/encoder_decoder_lstm/lightning_logs/checkpoints
  batch_size: 1
  epochs: 20 #20 #50 #3 #20 #20 #5 #20 #25




