experiment_name: Encoder Decoder LSTM
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project

seed: 42

dataset:
  preprocess:
    data_path: dataset
    frames_per_sec: 1 #15 #84
    standardise_data: True
    feature_engineering: True
    n_features: 3
    features: [index, middle, thumb]
    n_sequences: 30

model:
  module_name: encoder_decoder_lstm
  pl_class_name : LitEncoderDecoderLSTM
  script_path: models/encoder_decoder_lstm.py
  n_features: 3
  n_layers: 1
  n_hidden_units: 100

train:
  checkpoint_path: train/encoder_decoder_lstm/lightning_logs/checkpoints
  batch_size: 1
  epochs: 10
  gpus: 0
  kfold_path: cross-validation/encoder_decoder_kfold
  n_kfolds: 5
test:
  checkpoint_path: train/lightning_logs/checkpoints



