experiment_name: Encoder Decoder LSTM
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project

seed: 42
device: ['cpu', 'cuda']
dataset:
  preprocess:
    data_path: dataset
    frames_per_sec: 1 #15 #84
    standardise_data: True
    feature_engineering: True
    n_features: 3
    features: [index, middle, thumb]
    n_sequences: 30

model:
  module_name: lstm
  pl_class_name : LitManyToManyLSTM
  script_path: models/lstm.py
  n_layers: 1
  n_features: 3
  n_hidden_units: 100

train:
  checkpoint_path: train/lightning_logs/checkpoints
  batch_size: 1
  epochs: 10
  gpus: 0
  k_fold_path: cross-validation/lstm_kfold
  n_k_folds: 5

test:
  checkpoint_path: train/lightning_logs/checkpoints



