project_name: LSTM_KFOLD_Experiments
experiment_name: lstm_tactile_exp_10
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project
notes: testing many to many lstm on clutter and single dataset and whether feature engineering impact results
seed: 42

dataset:
  preprocess:
    clutter: True #get_files()
    single: True #get_files()
    tactile_frames_per_sec: data/tactile/with_feature_engineering/single_clutter_3fps.pt #directly loads dataset from data/tactile


model:
  module_name: many_to_many_lstm
  pl_class_name : LitManyToManyLSTM
  script_path: models/baseline_lstm_1_layer.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  n_features: 3
  n_hidden_units: 100
  n_layers: 1
  dropout: 0.0
  lr: 0.001

train:
  checkpoint_path: logging
  batch_size: 1
  epochs:  20
  n_kfolds: 5
  kfold_path: cross-validation/lstm_kfold