experiment_name: tcn_test
wb_project_name: TCN_Debugging
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project
notes: testing out tcn
seed: 42

dataset:
  preprocess:
    data_path: dataset #get_files()
    clutter: True #get_files()
    single: True #get_files()
    frames_per_sec: 1 #6 #1 #15  #read_data()
    feature_engineering: True #True #read_data()
    standardise_data: False #preprocess_dataset()
    normalize_data: True #preprocess_dataset()
    pad_data: True #preprocess_dataset()


model:
  module_name: tcn
  pl_class_name : LitTemporalConvNet
  script_path: models/tcn.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  n_features: 3
  n_hidden_units: 25
  n_levels: 8
  kernel_size: 7
  #dropout not in use
  dropout: 0.0
  lr: 0.001




train:
  checkpoint_path: logging
  batch_size: 1
  epochs: 20 #1 #15 #20 #20 #50 #3 #20 #20 #5 #20 #25