project_name: TCN_KFOLD
experiment_name: tcn_baseline_3
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project
notes: testing baseline tcn, again
seed: 42

dataset:
  preprocess:
    clutter: True #get_files()
    single: True #get_files()
    tactile_frames_per_sec: data/tactile/with_feature_engineering/single_clutter_3fps.pt #directly loads dataset from data/tactile

model:
  module_name: tcn
  pl_class_name : LitTemporalConvNet
  script_path: models/tcn.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  n_features: 3
  n_hid: 50
  n_levels: 5
  kernel_size: 8
  dropout: 0.2
  lr: 0.001




train:
  checkpoint_path: logging
  batch_size: 1
  epochs: 20 #1 #15 #20 #20 #50 #3 #20 #20 #5 #20 #25
  n_kfolds: 5
  kfold_path: cross-validation/tcn_kfold
