project_name: TCN_KFOLD_Clutter_Report
experiment_name: tcn_test2
main_dir: C:/Users/sonia/OneDrive - Queen Mary, University of London/Action-Segmentation-Project
notes: baseline model 
seed: 42
dataset:
  preprocess:
    clutter: True #get_files()
    single: False #get_files()
    tactile_frames_per_sec: data/tactile/with_feature_engineering/5fps/clutter_5fps_dataset_tensors.pt

model:
  module_name: tcn
  pl_class_name : LitTemporalConvNet
  script_path: models/tcn.py
  #set n_features according to preprocess dataset conditions
    #i.e. default is 3 (features = [index,thumb,middle] when feature engineering = True)
  n_features: 3
  n_hid: 75
  n_levels: 6
  kernel_size: 8
  dropout: 0.25
  lr: 0.001
  stride: 1

train:
  checkpoint_path: logging
  batch_size: 1
  epochs: 7
  n_kfolds: 5
  kfold_path: cross-validation/tcn_kfold
